"""P4 normalized artifact extractor.

Input is a *working copy* of an acquisition SQLite package containing a
messages table. The extractor does not use source reconstruction or ground
truth and does not expose synthetic-construction provenance to the examiner.

For the presentation dry-run, ACQ-DRY-001 is generated by
acquisition_simulator.py. For final casework, feed the normalized SQLite/CSV
export produced from the real ACQ-001 working copy.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

OUTPUT_FIELDS = [
    "evidence_id", "artifact_id", "acquisition_id", "device_id",
    "message_id", "conversation_id", "segment_id", "sender", "receiver",
    "timestamp_normalized", "message_text", "message_type",
    "reply_to_message_id", "attachment_id",
]


class ExtractionError(RuntimeError):
    pass


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with Path(path).open("rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def _pair_chat_id(sender: str, receiver: str) -> str:
    pair = "|".join(sorted([sender, receiver]))
    digest = hashlib.sha256(pair.encode("utf-8")).hexdigest()[:12].upper()
    return f"CHAT-{digest}"


def _load_metadata(conn: sqlite3.Connection) -> dict[str, str]:
    try:
        return dict(conn.execute("SELECT key,value FROM acquisition_metadata"))
    except sqlite3.Error:
        return {}


def extract_sqlite(input_db: Path) -> tuple[list[dict[str, str]], dict[str, str]]:
    if not Path(input_db).exists():
        raise ExtractionError(f"Input acquisition tidak ditemukan: {input_db}")
    conn = sqlite3.connect(f"file:{Path(input_db).resolve()}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    try:
        integrity = conn.execute("PRAGMA integrity_check").fetchone()[0]
        if integrity != "ok":
            raise ExtractionError(f"SQLite integrity_check gagal: {integrity}")
        metadata = _load_metadata(conn)
        source = conn.execute("""
            SELECT message_id,conversation_id,timestamp,sender_id,recipient_id,
                   message_text,message_type,reply_to_message_id,attachment_id
            FROM messages
            ORDER BY timestamp, message_id
        """).fetchall()
    except sqlite3.Error as exc:
        raise ExtractionError(f"Schema acquisition tidak kompatibel: {exc}") from exc
    finally:
        conn.close()

    rows: list[dict[str, str]] = []
    for i, r in enumerate(source, start=1):
        artifact_id = f"ART-{i:06d}"
        rows.append({
            "evidence_id": artifact_id,
            "artifact_id": artifact_id,
            "acquisition_id": metadata.get("acquisition_id", "ACQ-UNKNOWN"),
            "device_id": metadata.get("device_id", "DEV-UNKNOWN"),
            "message_id": r["message_id"],
            # merge segments into one examiner chat per participant pair
            "conversation_id": _pair_chat_id(r["sender_id"], r["recipient_id"]),
            "segment_id": r["conversation_id"],
            "sender": r["sender_id"],
            "receiver": r["recipient_id"],
            "timestamp_normalized": r["timestamp"],
            "message_text": r["message_text"],
            "message_type": r["message_type"] or "",
            "reply_to_message_id": r["reply_to_message_id"] or "",
            "attachment_id": r["attachment_id"] or "",
        })
    return rows, metadata


def validate(rows: list[dict[str, str]]) -> None:
    if not rows:
        raise ExtractionError("Tidak ada artifact yang diekstrak.")
    msg_ids = [r["message_id"] for r in rows]
    art_ids = [r["artifact_id"] for r in rows]
    if len(msg_ids) != len(set(msg_ids)):
        raise ExtractionError("Duplicate message_id di output P4.")
    if len(art_ids) != len(set(art_ids)):
        raise ExtractionError("Duplicate artifact_id di output P4.")
    for r in rows:
        try:
            datetime.fromisoformat(r["timestamp_normalized"])
        except ValueError as exc:
            raise ExtractionError(
                f"Timestamp invalid {r['message_id']}: {r['timestamp_normalized']}"
            ) from exc


def run(input_db: Path, output_csv: Path, manifest_path: Path) -> dict:
    rows, metadata = extract_sqlite(input_db)
    validate(rows)

    output_csv = Path(output_csv)
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    with output_csv.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=OUTPUT_FIELDS)
        w.writeheader()
        w.writerows(rows)

    manifest = {
        "status": "P4_EXTRACTION_PASS",
        "input_acquisition": str(input_db),
        "input_sha256": sha256_file(input_db),
        "output_artifact_csv": str(output_csv),
        "output_sha256": sha256_file(output_csv),
        "artifact_count": len(rows),
        "acquisition_id": metadata.get("acquisition_id", "ACQ-UNKNOWN"),
        "device_id": metadata.get("device_id", "DEV-UNKNOWN"),
        "chat_count": len({r["conversation_id"] for r in rows}),
        "segment_count": len({r["segment_id"] for r in rows}),
        "examiner_schema_excludes": [
            "source_provenance", "source_original_line",
            "ground_truth", "expected_entity_ids", "is_key_evidence",
        ],
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
    }
    manifest_path = Path(manifest_path)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return manifest


def main() -> None:
    p = argparse.ArgumentParser(description="Extract normalized P4 artifacts.")
    p.add_argument(
        "--input",
        default="runtime/private/ACQ-DRY-001/libera_simulated_acquisition.sqlite",
    )
    p.add_argument(
        "--output",
        default="runtime/working/P4/artifacts.csv",
    )
    p.add_argument(
        "--manifest",
        default="runtime/working/P4/artifact_manifest.json",
    )
    args = p.parse_args()
    try:
        m = run(Path(args.input), Path(args.output), Path(args.manifest))
    except ExtractionError as exc:
        print(f"[P4] ERROR: {exc}")
        raise SystemExit(1)
    print("[P4] PASS")
    print(f"  artifacts={m['artifact_count']} chats={m['chat_count']} segments={m['segment_count']}")
    print(f"  output_sha256={m['output_sha256']}")


if __name__ == "__main__":
    main()
